//this is the adminConstants.js file in the _constants folder

export const adminConstants = {
    LOGIN_REQUEST: 'ADMIN_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'ADMIN_LOGIN_FAILURE',
    LOGOUT: 'ADMIN_LOGOUT',
    REGISTER_REQUEST: 'ADMIN_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'ADMIN_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'ADMIN_REGISTER_FAILURE',
    GETALL_REQUEST: 'ADMIN_GETALL_REQUEST',
    GETALL_SUCCESS: 'ADMIN_GETALL_SUCCESS',
    GETALL_FAILURE: 'ADMIN_GETALL_FAILURE',
    DELETE_REQUEST: 'ADMIN_DELETE_REQUEST',
    DELETE_SUCCESS: 'ADMIN_DELETE_SUCCESS',
    DELETE_FAILURE: 'ADMIN_DELETE_FAILURE'
};


