//this is the developerConstants.js file in the _constants folder

export const developerConstants = {
    LOGIN_REQUEST: 'DEVELOPER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'DEVELOPER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'DEVELOPER_LOGIN_FAILURE',
    LOGOUT: 'DEVELOPER_LOGOUT',
    REGISTER_REQUEST: 'DEVELOPER_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'DEVELOPER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'DEVELOPER_REGISTER_FAILURE',
    GETALL_REQUEST: 'DEVELOPER_GETALL_REQUEST',
    GETALL_SUCCESS: 'DEVELOPER_GETALL_SUCCESS',
    GETALL_FAILURE: 'DEVELOPER_GETALL_FAILURE',
    DELETE_REQUEST: 'DEVELOPER_DELETE_REQUEST',
    DELETE_SUCCESS: 'DEVELOPER_DELETE_SUCCESS',
    DELETE_FAILURE: 'DEVELOPER_DELETE_FAILURE'
};

